# example_slideshow.yaml
# Complete example configuration for ESPHome slideshow component

esphome:
  name: living-room-display

esp32:
  board: esp32-p4-evboard
  flash_size: 16Mb
  cpu_frequency: 360MHz
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: yes
      disable_vfs_support_termios: false
      disable_vfs_support_select: false
      disable_vfs_support_dir: false
    sdkconfig_options:
      CONFIG_SPIRAM_XIP_FROM_PSRAM: "y" # Stop screen flashing during OTA
      CONFIG_SDMMC_HOST_DEFAULT: "y"
      CONFIG_LV_COLOR_SCREEN_TRANSP: "y" # Enable LVGL screen transparency

external_components:
  - source:
      type: local
      path: src

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    - delay: 2s # Wait for network to stabilize
    - slideshow.refresh_queue: my_slideshow

# Required for online_image
http_request:
  timeout: 10s
  useragent: esphome/slideshow

# Placeholder image shown while downloading
image:
  - file: "loading.png"
    id: loading_placeholder
    type: RGB565
    resize: 600x1024

# Create 3 online_image slots for the slideshow
# These will be dynamically loaded/unloaded as the slideshow advances
online_image:
  - url: "" # URL will be set dynamically
    id: slide_slot_0
    type: RGB565
    resize: 600x1024
    format: JPEG
    placeholder: loading_placeholder
    on_download_finished:
      - lambda: |-
          bool cached = x;  // x is true if loaded from cache
          id(my_slideshow).on_image_ready(0, cached);
    on_error:
      - lambda: |-
          id(my_slideshow).on_image_error(0);

  - url: ""
    id: slide_slot_1
    type: RGB565
    resize: 600x1024
    format: JPEG
    placeholder: loading_placeholder
    on_download_finished:
      - lambda: |-
          id(my_slideshow).on_image_ready(1, x);
    on_error:
      - lambda: |-
          id(my_slideshow).on_image_error(1);

  - url: ""
    id: slide_slot_2
    type: RGB565
    resize: 600x1024
    format: JPEG
    placeholder: loading_placeholder
    on_download_finished:
      - lambda: |-
          id(my_slideshow).on_image_ready(2, x);
    on_error:
      - lambda: |-
          id(my_slideshow).on_image_error(2);

# The slideshow component orchestrates the image slots
slideshow:
  id: my_slideshow
  backend_url: "https://your-backend.run.app/api/devices/living-room"
  device_id: "living-room"
  advance_interval: 10s
  queue_refresh_interval: 60s
  auto_advance: true

  image_slots:
    - slide_slot_0
    - slide_slot_1
    - slide_slot_2

  on_advance:
    - lambda: |-
        ESP_LOGI("slideshow", "Advanced to image %d", x);
        // Update display here if needed

  on_image_ready:
    - lambda: |-
        size_t index = index;
        bool cached = cached;
        ESP_LOGI("slideshow", "Image %d ready (cached: %s)", 
                 index, cached ? "yes" : "no");

  on_queue_updated:
    - lambda: |-
        ESP_LOGI("slideshow", "Queue updated: %d images", x);

  on_error:
    - lambda: |-
        ESP_LOGE("slideshow", "Error: %s", x.c_str());

logger:
  level: DEBUG
  logs:
    slideshow: DEBUG
    online_image: DEBUG
