# example_slideshow.yaml
# Complete example configuration for ESPHome slideshow component

external_components:
  - source:
      type: local
      path: components

substitutions:
  url: "https://storage.googleapis.com/milo-image-storage/processed/monotych/1024x600/03cf4498e532217ef6c9e1e2188f12fff7891914efcfb766f2baa5b7f0eb46fb.jpg"

esphome:
  name: living-room-display

esp32:
  board: esp32-p4-evboard
  flash_size: 16Mb
  cpu_frequency: 360MHz
  framework:
    type: esp-idf
    advanced:
      enable_idf_experimental_features: yes
      disable_vfs_support_termios: false
      disable_vfs_support_select: false
      disable_vfs_support_dir: false
    sdkconfig_options:
      CONFIG_SPIRAM_XIP_FROM_PSRAM: "y" # Stop screen flashing during OTA
      CONFIG_SDMMC_HOST_DEFAULT: "y"
      CONFIG_LV_COLOR_SCREEN_TRANSP: "y" # Enable LVGL screen transparency

psram:
  mode: hex
  speed: 200MHz

esp_ldo:
  - channel: 3
    id: dsi_phy_enable
    voltage: 2.5V
    adjustable: True

esp32_hosted:
  active_high: true
  variant: ESP32C6
  reset_pin: GPIO54
  cmd_pin: GPIO19
  clk_pin: GPIO18
  d0_pin: GPIO14
  d1_pin: GPIO15
  d2_pin: GPIO16
  d3_pin: GPIO17

display:
  - platform: mipi_dsi
    id: main_display
    model: JC1060P470
    update_interval: never
    reset_pin:
      number: GPIO05
    hsync_pulse_width: 20
    auto_clear_enabled: false

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  on_connect:
    - delay: 2s # Wait for network to stabilize
    # - slideshow.refresh_queue: my_slideshow

# Required for online_image
http_request:
  timeout: 10s
  useragent: esphome/slideshow

# Placeholder image shown while downloading
image:
  - file: ${url}
    id: loading_placeholder
    type: RGB565
    resize: 1024x600

# Create 3 online_image slots for the slideshow
# These will be dynamically loaded/unloaded as the slideshow advances
online_image:
  - url: ${url}
    id: slide_slot_0
    type: RGB565
    resize: 1024x600
    format: JPEG
    placeholder: loading_placeholder
    on_download_finished:
      - lambda: |-
          id(my_slideshow).on_image_ready(0);
    on_error:
      - lambda: |-
          id(my_slideshow).on_image_error(0);

  - url: ${url}
    id: slide_slot_1
    type: RGB565
    resize: 1024x600
    format: JPEG
    placeholder: loading_placeholder
    on_download_finished:
      - lambda: |-
          id(my_slideshow).on_image_ready(1);
    on_error:
      - lambda: |-
          id(my_slideshow).on_image_error(1);

  - url: ${url}
    id: slide_slot_2
    type: RGB565
    resize: 1024x600
    format: JPEG
    placeholder: loading_placeholder
    on_download_finished:
      - lambda: |-
          id(my_slideshow).on_image_ready(2);
    on_error:
      - lambda: |-
          id(my_slideshow).on_image_error(2);

# The slideshow component orchestrates the image slots
slideshow:
  id: my_slideshow
  
  # source: !lambda |-
  #   // Simple static queue builder
  #   std::vector<std::string> queue;
  #   queue.push_back("${url}");
  #   queue.push_back("${url}");
  #   queue.push_back("${url}");
  #   queue.push_back("${url}");
  #   return queue;

  advance_interval: 10s
  refresh_interval: 60s

  image_slots:
    - slide_slot_0
    - slide_slot_1
    - slide_slot_2

  on_advance:
    - lambda: |-
        ESP_LOGI("slideshow", "Advanced to image %d", x);
        // Update display here if needed

  on_image_ready:
    - lambda: |-
        ESP_LOGI("slideshow", "Image %d ready", index);

  on_queue_updated:
    - lambda: |-
        ESP_LOGI("slideshow", "Queue updated: %d images", x);

  on_error:
    - lambda: |-
        ESP_LOGE("slideshow", "Error: %s", x.c_str());

logger:
  level: DEBUG
  logs:
    slideshow: DEBUG
    online_image: DEBUG
